### ISSUE TITLE
Cannot find module 'ngx-page-scroll-core'  in Angular 8 after update to 7.0.2

### ISSUE THREAD

**Issue by Waftschi** [Nolanus/ngx-page-scroll#415]
After uprading to latest version Angular Application breaks. Return to 7.0.1 fixes the problem.

`
 Could not resolve ngx-page-scroll relative to [object Object]..
`
` Cannot find module 'ngx-page-scroll'.`

**Comment by ymallikreddy521** [comment]
even I have same issue. Any luck??

**Comment by ThRintelen** [comment]
Same problem in Angular 10

**Comment by erizoy** [comment]
` Cannot find module 'ngx-page-scroll-core'.`

Angular 9.0.2

**Comment by smorandi** [comment]
Seems to be an ivy issue with this. ngcc is not triggered with 7.0.2

**Comment by Nolanus** [comment]
Hi all. Sorry for the inconvenience, there was a problem with v7.0.2, resulting in the released files to be unusable for angular projects. v7.0.3 should fix this, please update to that version and let me know in case there any problems.
